name: Check Conflicts

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check_conflicts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run check_conflicts.py
        run: python check_conflicts.py
